global:
  scrape_interval: 15s # How often Prometheus collects metrics from all targets
  evaluation_interval: 15s # How often Prometheus evaluates alerting rules

# Alerting configuration (To handle alerts, not setting up in current App)
alerting:
  alertmanagers:
    - static_configs:
        - targets: []

# Load rules once and periodically evaluate them (Not setting up in current App)
rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

# Scrape configuration
scrape_configs:
  # Prometheus itself
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"] # Fixed: Should be port 9090, not 3000/api # # Container monitoring itself

  # Your Node.js application
  - job_name: "node-app"
    static_configs:
      - targets: ["host.docker.internal:3000"] # Access host machine from container
    metrics_path: "/api/metrics" # Your custom metrics path
    scrape_interval: 10s

  # System metrics from node-exporter
  - job_name: "node-exporter"
    static_configs:
      - targets: ["node-exporter:9100"] # Docker service name
    scrape_interval: 5s
